package com.example.springvue1.Dao;


import com.example.springvue1.pojo.ListUrl;


import java.util.List;

public interface ListUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listurl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Byte listurlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listurl
     *
     * @mbggenerated
     */
    int insert(ListUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listurl
     *
     * @mbggenerated
     */
    int insertSelective(ListUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listurl
     *
     * @mbggenerated
     */
    ListUrl selectByPrimaryKey(Byte listurlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listurl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ListUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listurl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ListUrl record);

    List<ListUrl> selectbylistUrl();
}