package com.example.springvue1.pojo;

import java.io.Serializable;

public class HomeZhu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homezhu.Hid
     *
     * @mbggenerated
     */
    private Byte hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homezhu.Hname
     *
     * @mbggenerated
     */
    private String hname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table homezhu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homezhu.Hid
     *
     * @return the value of homezhu.Hid
     *
     * @mbggenerated
     */
    public Byte getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homezhu.Hid
     *
     * @param hid the value for homezhu.Hid
     *
     * @mbggenerated
     */
    public void setHid(Byte hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homezhu.Hname
     *
     * @return the value of homezhu.Hname
     *
     * @mbggenerated
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homezhu.Hname
     *
     * @param hname the value for homezhu.Hname
     *
     * @mbggenerated
     */
    public void setHname(String hname) {
        this.hname = hname == null ? null : hname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homezhu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hid=").append(hid);
        sb.append(", hname=").append(hname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}